# Generated by Django 3.2.9 on 2021-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('hp', models.DecimalField(decimal_places=0, max_digits=4)),
                ('top_speed_mph', models.DecimalField(decimal_places=0, max_digits=3)),
                ('weight_kg', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
